class BadUserError(Exception):
	def __init__(self, user: str):
		self.message(f"Nie ma u≈ºytkownika o nazwie `{user}`")